# Write a program where the user is asked to enter two integers (divisor and dividend) and the quotient and the remainder fo their division is computed. (Both divisor and divident should be integers)
a = int(input("Enter the divisor: "))
b = int(input("Enter the dividend: "))
print(f"The quotient is: {a / b}")
print(f"The remainder is: {a % b}")